language: node_js

node_js: '8'

cache:
  directories:
    - $HOME/.npm

install:
  - npm install

script:
  - npm run prettier
  - npm run lint

jobs:
  include:
    - stage: test
      node_js: '8'
    - stage: release
      language: node_js
      node_js: '8'
      script:
        - npm run semantic-release

stages:
  - test
  - name: release
    if: branch = master AND type = push AND fork = false

branches:
  except:
   - /^v\d+\.\d+\.\d+$/
